/**
 * Whop checkout URLs — one env var per store product.
 * Paste your Whop checkout link for each product; leave blank until ready.
 * Buy Now redirects to that URL. Whop hosts the files after payment.
 *
 * Change links anytime in .env / Vercel env — no code change needed.
 */
export const WHOP_CHECKOUT_ENV_KEYS = [
  "NEXT_PUBLIC_WHOP_CHECKOUT_QUOTES",
  "NEXT_PUBLIC_WHOP_CHECKOUT_EVERYDAY",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_01",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_02",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_03",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_04",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_05",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_06",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_07",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_08",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_09",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_10",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_BASIC",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PREMIUM",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PRO",
  // Legacy aliases (old 5/10/canva names still resolve)
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK5",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK10",
  "NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_CANVA",
] as const;

export type WhopCheckoutEnvKey = (typeof WHOP_CHECKOUT_ENV_KEYS)[number];

/** Explicit map so Next.js inlines NEXT_PUBLIC_ values at build time. */
export function getWhopCheckoutEnvMap(): Record<string, string | undefined> {
  return {
    NEXT_PUBLIC_WHOP_CHECKOUT_QUOTES:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_QUOTES,
    NEXT_PUBLIC_WHOP_CHECKOUT_EVERYDAY:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_EVERYDAY,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_01:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_01,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_02:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_02,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_03:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_03,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_04:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_04,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_05:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_05,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_06:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_06,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_07:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_07,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_08:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_08,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_09:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_09,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_10:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_10,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_BASIC:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_BASIC ||
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK5,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PREMIUM:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PREMIUM ||
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK10,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PRO:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PRO ||
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_CANVA,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK5:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK5,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK10:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_PACK10,
    NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_CANVA:
      process.env.NEXT_PUBLIC_WHOP_CHECKOUT_KIDS_CANVA,
    // Legacy aliases (still work if you already set these)
    NEXT_PUBLIC_CHECKOUT_URL_QUOTES: process.env.NEXT_PUBLIC_CHECKOUT_URL_QUOTES,
    NEXT_PUBLIC_CHECKOUT_URL_EVERYDAY:
      process.env.NEXT_PUBLIC_CHECKOUT_URL_EVERYDAY,
    NEXT_PUBLIC_CHECKOUT_URL_KIDS_SINGLE:
      process.env.NEXT_PUBLIC_CHECKOUT_URL_KIDS_SINGLE,
    NEXT_PUBLIC_CHECKOUT_URL_KIDS_PACK5:
      process.env.NEXT_PUBLIC_CHECKOUT_URL_KIDS_PACK5,
    NEXT_PUBLIC_CHECKOUT_URL_KIDS_PACK10:
      process.env.NEXT_PUBLIC_CHECKOUT_URL_KIDS_PACK10,
    NEXT_PUBLIC_CHECKOUT_URL_KIDS_CANVA:
      process.env.NEXT_PUBLIC_CHECKOUT_URL_KIDS_CANVA,
    NEXT_PUBLIC_CHECKOUT_URL: process.env.NEXT_PUBLIC_CHECKOUT_URL,
  };
}

export function getProductCheckoutUrl(
  checkoutUrlEnv?: string,
): string | undefined {
  const byEnv = getWhopCheckoutEnvMap();

  if (checkoutUrlEnv) {
    const specific = byEnv[checkoutUrlEnv]?.trim();
    if (specific) return specific;
  }

  const fallback = byEnv.NEXT_PUBLIC_CHECKOUT_URL?.trim();
  return fallback || undefined;
}
